config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'posts#index'

  get 'about' => 'pages#about', as: "about"

  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: {minimum: 5}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @heading = 'Страничка про нас!'
    @text = 'Немного текста'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @post = Post.all
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
  #render plain: params[:post].inspect
  @post = Post.new(post_params)

  if  (@post.save)
    redirect_to @post
  else
    render "new"
  end
  end

  private def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simpleblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
      <h5 class="my-0 mr-md-auto font-weight-bold">My own site</h5>
      <nav class="my-2 my-md-0 mr-md-3">
        <span class="p-2 text-dark" ><%= link_to "Главная страница", root_path %></span>
        <span class="p-2 text-dark" ><%= link_to "Про нас", about_path %></span>

        <% if user_signed_in? %>
          <span class="p-2 text-dark" ><%= link_to "Добавление статьи", new_post_path %></span>
          <span class="p-2 text-dark" >Logged in as <strong><%= current_user.email %></strong></span>
          <span class="p-2 text-dark" ><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></span> |
          <span class="p-2 text-dark" ><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></span>
        <% else %>
          <span class="p-2 text-dark" ><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></span> |
          <span class="p-2 text-dark" ><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></span>
        <% end %>


      </nav>
    </div>
    <div class="container">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>

      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h4><%= @heading %></h4>
<p><%= @text %></p>

app/views/posts/index.html.erb
<h1>Все наши посты</h1>
<% @post.each do |post| %>
  <div class="alert alert-light">
    <h3><%= post.title %></h3>
    <p><%= post.body %></p>
    <%= link_to "Читать далее", post_path(post), :class => "btn btn-outline-primary" %>
  </div>
  <br>
<% end %>

app/views/posts/new.html.erb
<h2>Добавление нового поста</h2>
<%= form_for :post, url: posts_path do |f| %>
<% if @post.errors.any? %>
<% @post.errors.full_messages.each do |msg| %>
  <div class="alert alert-danger"><%= msg %></div>
  <% end %>
<% end %>
<p>
Название<br>
<%= f.text_field(:title, {:class => "form-control"}) %>
</p>
<p>
Текст статьи<br>
<%= f.text_area(:body, {:class => "form-control"})%>
</p>
<p>
<%= f.submit({:class => "btn btn-success"}) %>
</p>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.body %></p>